#!/bin/bash
set -x

gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep "\.go$")
[ ! -z "$gofiles" ] && gofmt -w $gofiles

jsxfiles=$(git diff --cached --name-only --diff-filter=ACM | grep "\.jsx$")
[ ! -z "${jsxfiles}" ] && npm run sort-props ${jsxfiles};

pyfiles=$(git diff --cached --name-only --diff-filter=ACM | grep "\.py$")
[ ! -z "${pyfiles}" ] && yapf -i ${pyfiles};

cfiles=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.cpp$|\.hpp$|\.h$|\.c$")
#[ ! -z "${cfiles}" ] && 

for i in ${cfiles}; do
  clang-format -i "${i}";
done


